name: Linux (Vulkan)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt-get install libasound2-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libxi-dev libxcursor-dev libgtk-3-dev libvulkan-dev --yes --quiet
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get Node.js
      run: git clone https://github.com/armory3d/nodejs_bin.git --depth 1
    - name: Apply patch
      run: git apply patch/vulkan_raytrace.diff --directory=Kinc
    - name: Get glsl_to_spirv
      run: git clone --recursive https://github.com/armory3d/glsl_to_spirv Libraries/glsl_to_spirv
    - name: Compile
      run: nodejs_bin/node-linux64 Kinc/make -g vulkan --raytrace vkrt --compiler clang --compile
