name: macOS (Metal)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Apply patch
      run: git apply Patches/metal_raytrace.diff --directory=Kinc
    - name: Compile
      run: Kinc/make -g metal --compile
