name: Windows (Direct3D12)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Unpack v8_monolith
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: v8/libraries/win32/release/v8_monolith.7z
        pathTarget: v8/libraries/win32/release/
    - name: Apply patch
      run: git apply Patches/d3d12_raytrace.diff --directory=Kinc
    - name: Compile
      run: Kinc/make -g direct3d12 --compile
